### ISSUE TITLE
Settings Menu not opening & not able to Uninstall 

### ISSUE THREAD

**Issue by ghost** [dexoref/MyEmployeeAttendanceRegister#11]
Hello,
Tried your application "electric_eel" in Mobile device with  Android 7.0 
Layout is good, when I clicked in Setting, nothing happened.. 
Other menu options working.

Uninstall:
Application not showing in Device Settings Application menu for Uninstall. 

Thank you.

**Comment by sylveryte** [comment]
Thank you for trying this app. Settings isn't finished. Development is halted. And for your uninstallation look for application name "My Employee Attendance Register".

**Comment by ghost** [comment]
Thank You..
